resume: null
load_encoder: true
load_fuse_generator: true
device: cuda:0
image_size: 224
K: 1
deterministic: true

train:
  lr: 1.0e-4
  num_epochs: 50
  batch_size: 16
  num_workers: 8
  log_path: runs/ondamm-smirk-ft
  log_losses_every: 10
  visualize_every: 100
  mask_ratio: 0.01
  mask_dilation_radius: 10
  save_every: 2
  use_wandb: false
  Ke: 1
  use_base_model_for_regularization: true
  resume_epoch: 0
  train_scale_min: 1.2
  train_scale_max: 1.8
  test_scale: 1.6

  loss_weights:
    landmark_loss: 100.0
    perceptual_vgg_loss: 10.0
    reconstruction_loss: 10.0
    emotion_loss: 0.0
    jaw_regularization: 0.01
    expression_regularization: 0.001
    shape_regularization: 100.0
    cycle_loss: 1.0
    mica_loss: 0.0

  optimize_pose: false
  optimize_shape: false
  optimize_expression: true
  freeze_encoder_in_second_path: false
  freeze_generator_in_second_path: false

arch:
  backbone_pose: tf_mobilenetv3_small_minimal_100
  backbone_shape: tf_mobilenetv3_large_minimal_100
  backbone_expression: tf_mobilenetv3_large_minimal_100
  num_expression: 50
  num_shape: 300
  use_eyelids: true
  enable_fuse_generator: true

render:
  full_head: false

dataset:
  root: /srv/ondamm/data/processed
  manifest: /srv/ondamm/manifests/split-manifest.jsonl
